default:
  image: maven:3.9.9

stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - echo "Build App"
    - ./mvnw clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/
    expire_in: 1 day

lint:
  stage: lint
  script:
    - echo "Lint App"
    - ./mvnw pmd:check

test:
  stage: test
  script:
    - echo "Test App"
    - ./mvnw test

deploy-master:
  image: docker:27
  script:
    - docker login
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" -f src/main/docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
  only:
    - master